apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-deployment
  namespace: scheduling-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
        feature: node-selector
    spec:
      nodeSelector:
        workload: coolapp
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"