apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-taint-deployment
  namespace: scheduling-learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
        feature: taints-tolerations
    spec:
      tolerations:
      - key: dedicated
        operator: "Equal"
        value: coolapp
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"