apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
  labels:
    {{- include "gratitudeapp.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.database.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.database.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.size }}
